version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.20
    commands: 
      - echo "node"
  pre_build:
    commands:
      - echo $(pwd)
      - cd backend
      - echo $(pwd)
      - npm install
  build:
    commands:
      - echo $(pwd)
      - npm run build
artifacts:
  files:
    - "*"
